apiVersion: apps/v1
kind: Deployment
metadata:
  name: create-user-api
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: create-user-api
  template:
    metadata:
      labels:
        app: create-user-api
    spec:
      nodeSelector:
        kubernetes.io/hostname: knode1.garrahan.gov.ar
      containers:
        - name: api
          image: ghcr.io/leanjperalta/python-create-user-api:347650c55fc921902c0a129f2b505513bb7777e2
          ports:
            - containerPort: 8000
          env:
            - name: LP_PASS
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: lp_pass
            - name: DDS_PASS
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: dds_pass
